features<-read.table("./UCI HAR Dataset/features.txt", col.names = c("n","functions"))
activities<-read.table("./UCI HAR Dataset/activity_labels.txt", col.names = c("code", "activity"))
subject_test<-read.table("./UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
x_test<-read.table("./UCI HAR Dataset/test/X_test.txt", col.names = features$functions)
y_test<-read.table("./UCI HAR Dataset/test/y_test.txt", col.names = "code")
subject_train<- read.table("./UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
x_train<-read.table("./UCI HAR Dataset/train/X_train.txt", col.names = features$functions)
y_train<-read.table("./UCI HAR Dataset/train/y_train.txt", col.names = "code")
x<-rbind(x_train, x_test)
y<-rbind(y_train, y_test)
subject<-rbind(subject_train, subject_test)
merged<-cbind(subject, y, x)
setDT(merged)
tidy<-merged %>% select(subject, code, contains("mean"), contains("std"))
tidy$code<-activities[tidy$code, "activity"]
names(tidy)[2] = "activity"
names(tidy)<-gsub("Acc", "Accelerometer", names(tidy))
names(tidy)<-gsub("Gyro", "Gyroscope", names(tidy))
names(tidy)<-gsub("BodyBody", "Body", names(tidy))
names(tidy)<-gsub("Mag", "Magnitude", names(tidy))
names(tidy)<-gsub("^t", "Time", names(tidy))
names(tidy)<-gsub("^f", "Frequency", names(tidy))
names(tidy)<-gsub("tBody", "TimeBody", names(tidy))
names(tidy)<-gsub("-mean()", "Mean", names(tidy), ignore.case = TRUE)
names(tidy)<-gsub("-std()", "STD", names(tidy), ignore.case = TRUE)
names(tidy)<-gsub("-freq()", "Frequency", names(tidy), ignore.case = TRUE)
names(tidy)<-gsub("angle", "Angle", names(tidy))
names(tidy)<-gsub("gravity", "Gravity", names(tidy))
anotherTidyData<-tidy %>% group_by(activity, subject) %>%
  summarize_all(funs(mean))
write.table(anotherTidyData, "./UCI HAR Dataset/output.txt", row.name=FALSE)